name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          cd /var/www/html

          sudo git pull origin main

          npm install

          npm run build

          sudo rm -rf /var/www/html/*

          sudo cp -r dist/* /var/www/html/

          sudo systemctl restart nginx

          EOF
